FROM node:16 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:16 as production

WORKDIR /app

COPY --from=build /app/dist ./dist

COPY --from=build /app/package*.json ./

COPY --from=build /app/dist ./dist

RUN npm install --only=production

CMD ["npm", "run", "start:prod"]
